name: Build APK
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build with Buildozer
        uses: ArtemBernatskyy/buildozer-action@v1
        with:
          workdir: .
          buildozer_version: master
      - name: Upload APK
        uses: actions/actions-tool@v2
        with:
          name: ruijieturbo-apk
          path: bin/*.apk

